### ISSUE TITLE
handout 4.1: #points to determine the n-th derivative

### ISSUE THREAD

**Issue by chenzhaiyu** [tudelft3d/geo1004_handouts#2]
The n_1 [here](https://github.com/tudelft3d/geo1004_handouts/blob/43a21ed1b6e802ad0a309687aeb2bd92abe05f63/handout4.1/curves.tex#L203) as #points to determine the n-th derivative is confusing...

**Comment by kenohori** [comment]
Thanks! It should be n+1 points. Will compile and upload the updated handouts now.
