### ISSUE TITLE
handout7.1 referal incorrect

### ISSUE THREAD

**Issue by LaurensVanRijssel** [tudelft3d/geo1004_handouts#3]
In reader 7.1 1.1 (p2) is referred to lesson 2.2 (3D delaunaytriangulation)
I believe this should be lesson3.1 (voxelisation)

**Comment by hugoledoux** [comment]
no it shouldn't.

Voxelisation as explained in les3.1 is *for objects* only, and not for fields. In les2.2 there are sub-sections about interpolation based on the VD/DT.
