### ISSUE TITLE
Possible topological issue with marching tetrahedra

### ISSUE THREAD

**Issue by LaurensVanRijssel** [tudelft3d/geo1004_handouts#4]
In the case of creating a isoplane through a set of connected tetrahedra one case got my attention:
when 3 vertices are on the isoline of the tetrahedron it is stated that the triangle formed by these vertices is the isoplane. However, the other tetrahedron incident to this face will do the same. I assume this case is thought of, but I just noticed it, ofcourse a simple solution is to only include the face when the opposite vertex is lower (of higher).

theoretically also a case could exist where all vertices have the value of the isoline, though this is not a very usefull situation

**Comment by hugoledoux** [comment]
Yes, all correct. 

Although the sentences to deal with those were there: https://github.com/tudelft3d/geo1004_handouts/blob/master/handout7.1/conversion.tex#L220

If the 4 vertices are equal, then you extract the 4 triangles indeed.
